<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { Bell, Check, ChevronRight, Eye, EyeOff, Flame, Heart, Lock, LogOut, Mail, Menu, MonitorPlay, Play, Plus, Search, Sparkles, Star, X } from 'lucide-vue-next';

type Anime = { title: string; subtitle: string; genre: string; rating: string; episodes: string; image: string; progress?: number };
const featured: Anime = { title: 'Solo Leveling', subtitle: 'Arise from the shadows', genre: 'Action • Fantasy', rating: '9.4', episodes: 'Season 2', image: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1800&q=90', progress: 62 };
const trending: Anime[] = [
  { title: 'The Apothecary Diaries', subtitle: 'Season 2', genre: 'Mystery', rating: '9.1', episodes: '24 Episodes', image: 'https://images.unsplash.com/photo-1541562232579-512a21360020?auto=format&fit=crop&w=700&q=85' },
  { title: 'Blue Lock', subtitle: 'VS. U-20 Japan', genre: 'Sports', rating: '8.8', episodes: '14 Episodes', image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=700&q=85' },
  { title: 'Frieren', subtitle: 'Beyond Journey’s End', genre: 'Adventure', rating: '9.6', episodes: '28 Episodes', image: 'https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?auto=format&fit=crop&w=700&q=85' },
  { title: 'Dandadan', subtitle: 'Occult Mystery', genre: 'Supernatural', rating: '8.9', episodes: '12 Episodes', image: 'https://images.unsplash.com/photo-1617791160505-6f00504e3519?auto=format&fit=crop&w=700&q=85' },
  { title: 'Kaiju No. 8', subtitle: 'Monster Sweeper', genre: 'Action', rating: '8.7', episodes: '12 Episodes', image: 'https://images.unsplash.com/photo-1519608487953-e999c86e7452?auto=format&fit=crop&w=700&q=85' }
];
const continueWatching: Anime[] = [
  { title: 'Attack on Titan', subtitle: 'The Final Chapters', genre: 'Action', rating: '9.8', episodes: 'Episode 7', image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=85', progress: 74 },
  { title: 'Spy x Family', subtitle: 'Code: White', genre: 'Comedy', rating: '8.9', episodes: 'Episode 4', image: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=800&q=85', progress: 38 },
  { title: 'One Piece', subtitle: 'Egghead Arc', genre: 'Adventure', rating: '9.2', episodes: 'Episode 1122', image: 'https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format&fit=crop&w=800&q=85', progress: 86 }
];
const genres = ['Action', 'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Romance', 'Sci-Fi'];
const search = ref(''); const activeGenre = ref('All'); const loginOpen = ref(false); const mobileMenuOpen = ref(false); const showPassword = ref(false);
const email = ref(''); const password = ref(''); const rememberMe = ref(true); const loginError = ref(''); const profileName = ref(''); const toast = ref('');
const isLoggedIn = computed(() => Boolean(profileName.value));
const filteredTrending = computed(() => trending.filter((anime) => {
  const query = search.value.trim().toLowerCase();
  return (activeGenre.value === 'All' || anime.genre === activeGenre.value) && (!query || `${anime.title} ${anime.subtitle} ${anime.genre}`.toLowerCase().includes(query));
}));
onMounted(() => { profileName.value = localStorage.getItem('watch-anime-user') || ''; });
function notify(message: string) { toast.value = message; window.setTimeout(() => { toast.value = ''; }, 2600); }
function openLogin() { loginError.value = ''; loginOpen.value = true; mobileMenuOpen.value = false; }
function login() {
  if (!email.value.includes('@') || password.value.length < 6) { loginError.value = 'Enter a valid email and a password with at least 6 characters.'; return; }
  profileName.value = email.value.split('@')[0].replace(/[._-]/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
  if (rememberMe.value) localStorage.setItem('watch-anime-user', profileName.value);
  loginOpen.value = false; password.value = ''; notify(`Welcome back, ${profileName.value}!`);
}
function logout() { localStorage.removeItem('watch-anime-user'); profileName.value = ''; notify('You have been logged out.'); }
function watch(anime: Anime) { notify(`Opening ${anime.title}…`); }
</script>

<template>
  <main class="min-h-screen overflow-x-hidden bg-[#080a12] text-white selection:bg-fuchsia-500/40">
    <div class="pointer-events-none fixed inset-0 -z-10 bg-[radial-gradient(circle_at_8%_5%,rgba(177,43,255,.17),transparent_25%),radial-gradient(circle_at_88%_24%,rgba(20,108,255,.14),transparent_25%)]"></div>
    <header class="sticky top-0 z-40 border-b border-white/8 bg-[#080a12]/80 backdrop-blur-xl">
      <div class="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
        <a class="flex items-center gap-2.5 font-display text-xl font-bold tracking-tight" href="#"><span class="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-fuchsia-500 to-violet-600 shadow-lg shadow-fuchsia-500/25"><Play class="ml-0.5 h-4 w-4 fill-white" /></span>Watch<span class="text-fuchsia-400">Anime</span></a>
        <nav class="hidden items-center gap-7 text-sm font-medium text-slate-300 md:flex"><a class="text-white" href="#home">Home</a><a href="#trending" class="transition hover:text-white">Trending</a><a href="#continue" class="transition hover:text-white">My List</a><a href="#genres" class="transition hover:text-white">Genres</a></nav>
        <div class="hidden items-center gap-3 md:flex">
          <label class="group flex h-10 w-52 items-center gap-2 rounded-xl border border-white/8 bg-white/5 px-3 transition focus-within:border-fuchsia-400/60"><Search class="h-4 w-4 text-slate-500 group-focus-within:text-fuchsia-300" /><input v-model="search" class="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-slate-500" placeholder="Search anime" /></label>
          <button class="grid h-10 w-10 place-items-center rounded-xl text-slate-300 transition hover:bg-white/8 hover:text-white" @click="notify('No new notifications.')"><Bell class="h-4 w-4" /></button>
          <button v-if="!isLoggedIn" class="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-slate-950 transition hover:bg-fuchsia-100" @click="openLogin">Log in</button>
          <div v-else class="flex items-center gap-2"><button class="flex items-center gap-2 rounded-xl bg-white/8 py-2 pl-2 pr-3 text-sm font-semibold" @click="notify('Profile settings are coming soon.')"><span class="grid h-7 w-7 place-items-center rounded-lg bg-gradient-to-br from-violet-500 to-fuchsia-500 text-xs">{{ profileName.charAt(0) }}</span>{{ profileName }}</button><button class="p-2 text-slate-400 hover:text-white" title="Log out" @click="logout"><LogOut class="h-4 w-4" /></button></div>
        </div>
        <button class="grid h-10 w-10 place-items-center rounded-xl bg-white/6 md:hidden" @click="mobileMenuOpen = !mobileMenuOpen"><X v-if="mobileMenuOpen" class="h-5 w-5" /><Menu v-else class="h-5 w-5" /></button>
      </div>
      <div v-if="mobileMenuOpen" class="border-t border-white/8 bg-[#0d101b] px-5 py-4 md:hidden"><div class="flex flex-col gap-4 text-sm text-slate-300"><a href="#trending" @click="mobileMenuOpen = false">Trending</a><a href="#continue" @click="mobileMenuOpen = false">My List</a><button v-if="!isLoggedIn" class="w-fit rounded-lg bg-white px-4 py-2 font-bold text-slate-950" @click="openLogin">Log in</button><button v-else class="w-fit text-left text-fuchsia-300" @click="logout">Log out</button></div></div>
    </header>

    <section id="home" class="relative mx-auto max-w-7xl px-5 pb-14 pt-8 lg:px-8 lg:pt-12">
      <div class="absolute inset-x-0 top-0 h-[460px] overflow-hidden rounded-b-[3rem]"><img :src="featured.image" class="h-full w-full object-cover opacity-45" alt="Featured anime backdrop" /><div class="absolute inset-0 bg-gradient-to-r from-[#080a12] via-[#080a12]/65 to-[#080a12]/20"></div><div class="absolute inset-0 bg-gradient-to-t from-[#080a12] via-transparent"></div></div>
      <div class="relative grid min-h-[410px] items-end gap-8 pb-5 lg:grid-cols-[1fr_290px]">
        <div class="max-w-2xl"><div class="mb-4 inline-flex items-center gap-2 rounded-full border border-fuchsia-400/25 bg-fuchsia-500/10 px-3 py-1.5 text-xs font-semibold text-fuchsia-200"><Sparkles class="h-3.5 w-3.5" /> #1 in Japan today</div><p class="mb-3 text-sm font-medium text-slate-300">{{ featured.genre }} <span class="mx-2 text-slate-600">•</span> {{ featured.episodes }}</p><h1 class="font-display text-5xl font-bold leading-none tracking-tight sm:text-7xl">{{ featured.title }}</h1><p class="mt-5 max-w-xl text-sm leading-6 text-slate-300 sm:text-base">The world’s weakest hunter discovers a mysterious system that gives him the power to level up beyond anyone’s imagination.</p><div class="mt-7 flex flex-wrap gap-3"><button class="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-950 transition hover:scale-[1.02]" @click="watch(featured)"><Play class="h-4 w-4 fill-slate-950" /> Watch episode 1</button><button class="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/8 px-5 py-3 text-sm font-semibold transition hover:bg-white/15" @click="notify('Added Solo Leveling to your list.')"><Plus class="h-4 w-4" /> My list</button></div></div>
        <div class="hidden rounded-2xl border border-white/10 bg-[#111521]/70 p-4 backdrop-blur lg:block"><div class="mb-3 flex items-center justify-between text-xs text-slate-400"><span>Continue watching</span><span>{{ featured.progress }}%</span></div><div class="relative aspect-video overflow-hidden rounded-xl"><img :src="featured.image" class="h-full w-full object-cover" alt="Solo Leveling" /><button class="absolute inset-0 grid place-items-center bg-slate-950/20" @click="watch(featured)"><span class="grid h-11 w-11 place-items-center rounded-full bg-white text-slate-900"><Play class="ml-0.5 h-4 w-4 fill-current" /></span></button></div><div class="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div class="h-full rounded-full bg-fuchsia-500" :style="{ width: `${featured.progress}%` }"></div></div></div>
      </div>
    </section>

    <section id="continue" class="mx-auto max-w-7xl px-5 py-8 lg:px-8"><div class="mb-5 flex items-end justify-between"><div><p class="mb-1 text-xs font-bold uppercase tracking-[.18em] text-fuchsia-400">Pick up where you left off</p><h2 class="font-display text-2xl font-bold">Continue watching</h2></div><button class="inline-flex items-center gap-1 text-sm font-semibold text-slate-300 hover:text-white">See all <ChevronRight class="h-4 w-4" /></button></div><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><article v-for="anime in continueWatching" :key="anime.title" class="group overflow-hidden rounded-2xl border border-white/8 bg-[#10131e] transition hover:-translate-y-1 hover:border-white/20"><div class="relative aspect-[16/8]"><img :src="anime.image" :alt="anime.title" class="h-full w-full object-cover opacity-80 transition duration-500 group-hover:scale-105 group-hover:opacity-100" /><button class="absolute inset-0 grid place-items-center bg-slate-950/20 opacity-0 transition group-hover:opacity-100" @click="watch(anime)"><span class="grid h-12 w-12 place-items-center rounded-full bg-white text-slate-900"><Play class="ml-0.5 h-5 w-5 fill-current" /></span></button></div><div class="p-4"><div class="mb-2 flex justify-between text-xs text-slate-400"><span>{{ anime.episodes }}</span><span>{{ anime.progress }}% watched</span></div><div class="h-1.5 overflow-hidden rounded-full bg-white/10"><div class="h-full rounded-full bg-fuchsia-500" :style="{ width: `${anime.progress}%` }"></div></div><h3 class="mt-3 font-semibold">{{ anime.title }}</h3></div></article></div></section>

    <section id="trending" class="mx-auto max-w-7xl px-5 py-14 lg:px-8"><div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="mb-1 text-xs font-bold uppercase tracking-[.18em] text-fuchsia-400">New this week</p><h2 class="font-display text-3xl font-bold">Trending now</h2></div><label class="flex h-10 items-center gap-2 rounded-xl border border-white/8 bg-white/5 px-3 sm:hidden"><Search class="h-4 w-4 text-slate-500" /><input v-model="search" class="w-full bg-transparent text-sm outline-none placeholder:text-slate-500" placeholder="Search anime" /></label></div><div v-if="filteredTrending.length" class="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5"><article v-for="(anime, index) in filteredTrending" :key="anime.title" class="group cursor-pointer" @click="watch(anime)"><div class="relative aspect-[3/4] overflow-hidden rounded-2xl bg-white/5"><img :src="anime.image" :alt="anime.title" class="h-full w-full object-cover transition duration-500 group-hover:scale-110" /><div class="absolute inset-x-0 bottom-0 h-1/2 bg-gradient-to-t from-[#080a12] to-transparent"></div><span class="absolute left-3 top-3 grid h-7 w-7 place-items-center rounded-lg bg-fuchsia-500 text-xs font-black">{{ index + 1 }}</span><button class="absolute bottom-3 right-3 grid h-9 w-9 place-items-center rounded-full bg-white text-slate-950 opacity-0 shadow-lg transition group-hover:opacity-100"><Play class="ml-0.5 h-3.5 w-3.5 fill-current" /></button></div><h3 class="mt-3 truncate font-semibold">{{ anime.title }}</h3><div class="mt-1 flex items-center gap-2 text-xs text-slate-400"><span>{{ anime.genre }}</span><span class="flex items-center gap-1 text-amber-300"><Star class="h-3 w-3 fill-current" />{{ anime.rating }}</span></div></article></div><div v-else class="rounded-2xl border border-dashed border-white/15 px-6 py-16 text-center text-slate-400">No shows match “{{ search }}”. Try another title.</div></section>

    <section id="genres" class="border-y border-white/7 bg-white/[.025]"><div class="mx-auto max-w-7xl px-5 py-14 lg:px-8"><div class="mb-6 flex items-center justify-between"><div><p class="mb-1 text-xs font-bold uppercase tracking-[.18em] text-fuchsia-400">Explore your mood</p><h2 class="font-display text-3xl font-bold">Browse by genre</h2></div><Flame class="h-7 w-7 text-fuchsia-400" /></div><div class="flex flex-wrap gap-3"><button :class="activeGenre === 'All' ? 'border-fuchsia-400 bg-fuchsia-500 text-white' : 'border-white/10 bg-white/5 text-slate-300 hover:border-white/30'" class="rounded-xl border px-5 py-3 text-sm font-semibold transition" @click="activeGenre = 'All'">All</button><button v-for="genre in genres" :key="genre" :class="activeGenre === genre ? 'border-fuchsia-400 bg-fuchsia-500 text-white' : 'border-white/10 bg-white/5 text-slate-300 hover:border-white/30'" class="rounded-xl border px-5 py-3 text-sm font-semibold transition" @click="activeGenre = genre">{{ genre }}</button></div></div></section>
    <footer class="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-10 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div class="flex items-center gap-2 font-display font-bold text-slate-300"><MonitorPlay class="h-4 w-4 text-fuchsia-400" /> Watch-Anime</div><p>Made for fans who always need one more episode.</p><div class="flex gap-4"><a href="#" class="hover:text-white">Help</a><a href="#" class="hover:text-white">Terms</a><a href="#" class="hover:text-white">Privacy</a></div></footer>

    <Transition name="fade"><div v-if="toast" class="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-white/15 bg-[#1c2030] px-4 py-3 text-sm font-medium shadow-2xl shadow-black/40"><Check class="mr-2 inline h-4 w-4 text-emerald-400" />{{ toast }}</div></Transition>
    <Transition name="fade"><div v-if="loginOpen" class="fixed inset-0 z-50 grid place-items-center bg-[#05060b]/80 p-4 backdrop-blur-sm" @click.self="loginOpen = false"><form class="relative w-full max-w-md rounded-3xl border border-white/12 bg-[#111521] p-7 shadow-2xl shadow-black/60" @submit.prevent="login"><button type="button" class="absolute right-5 top-5 text-slate-400 hover:text-white" @click="loginOpen = false"><X class="h-5 w-5" /></button><div class="mb-7 grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-fuchsia-500 to-violet-600"><Play class="ml-0.5 h-5 w-5 fill-white" /></div><h2 class="font-display text-3xl font-bold">Welcome back</h2><p class="mt-2 text-sm text-slate-400">Log in to sync your list and keep watching.</p><div class="mt-6 space-y-4"><label class="block text-sm font-medium text-slate-300">Email<div class="relative mt-2"><Mail class="absolute left-3 top-3 h-4 w-4 text-slate-500" /><input v-model.trim="email" type="email" class="w-full rounded-xl border border-white/10 bg-white/5 py-3 pl-10 pr-4 outline-none transition focus:border-fuchsia-400" placeholder="you@example.com" /></div></label><label class="block text-sm font-medium text-slate-300">Password<div class="relative mt-2"><Lock class="absolute left-3 top-3 h-4 w-4 text-slate-500" /><input v-model="password" :type="showPassword ? 'text' : 'password'" class="w-full rounded-xl border border-white/10 bg-white/5 py-3 pl-10 pr-11 outline-none transition focus:border-fuchsia-400" placeholder="At least 6 characters" /><button type="button" class="absolute right-3 top-3 text-slate-500 hover:text-white" @click="showPassword = !showPassword"><EyeOff v-if="showPassword" class="h-4 w-4" /><Eye v-else class="h-4 w-4" /></button></div></label><label class="flex cursor-pointer items-center gap-2 text-sm text-slate-400"><input v-model="rememberMe" type="checkbox" class="accent-fuchsia-500" /> Keep me signed in</label></div><p v-if="loginError" class="mt-4 text-sm text-rose-300">{{ loginError }}</p><button class="mt-6 w-full rounded-xl bg-white py-3 font-bold text-slate-950 transition hover:bg-fuchsia-100" type="submit">Log in to Watch-Anime</button><p class="mt-4 text-center text-xs text-slate-500">New here? Enter your email to create a local profile.</p></form></div></Transition>
  </main>
</template>
